services:
  oss-t3-chat:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount a volume for the SQLite database to persist data
      - ./docker-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/auth/session"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 